function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 16-Nov-2022 22:15:54

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop = 0.3;  % Stopband Frequency
    % Fpass = 0.5;  % Passband Frequency
    % Astop = 80;   % Stopband Attenuation (dB)
    % Apass = 1;    % Passband Ripple (dB)
    % Fs    = 500;  % Sampling Frequency
    %
    % h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'MatchExactly', 'both', ...
    %     'SystemObject', true,...
    %      UseLegacyBiquadFilter=true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.99998200620977 1 1 -1.9995450777113 ...
        0.999584716674151; 1 -1.99998721849104 1 1 -1.99806359188466 ...
        0.998117681282885; 1 -1.99999550827007 1 1 -1.99158011863672 ...
        0.991712551650991; 1 -1 0 1 -0.974289000448855 0], ...
        'ScaleValues', [0.241185130133525; 0.999048510628759; ...
        0.995824285815366; 4.09201920814149; 1]);
end

s = double(x);
y = step(Hd,s);

