function Hd = highpass
%HIGHPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 23-Nov-2022 21:49:03

% IIR Least P-th norm Highpass filter designed using the IIRLPNORM
% function.

% All frequency values are in Hz.
Fs = 500;  % Sampling Frequency

Nb    = 10;                   % Numerator Order
Na    = 10;                   % Denominator Order
Fstop = 0.29999999999999999;  % Stopband Frequency
Fpass = 0.5;                  % Passband Frequency
Wstop = 1;                    % Stopband Weight
Wpass = 1;                    % Passband Weight
P     = [2 128];              % P'th norm
dens  = 20;                   % Density Factor

F = [0 Fstop Fpass Fs/2]/(Fs/2);

% Calculate the coefficients using the IIRLPNORM function.
[b,a,err,sos_var,g] = iirlpnorm(Nb, Na, F, F, [0 0 1 1], [Wstop Wstop ...
                                Wpass Wpass], P, {dens});
Hd                  = dfilt.df2sos(sos_var, g);

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);



% [EOF]
